<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>
            dotnet-AlasdairCooper.Reference.Api.Migrator-48f096be-a07a-42e6-a7cb-3eb9b483a219</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="[13.0.2]" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="[11.0.0-rc.1.26425.128]">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference
            Include="..\..\orchestration\service-defaults\AlasdairCooper.Reference.Orchestration.ServiceDefaults.csproj" />
        <ProjectReference Include="..\..\shared\AlasdairCooper.Reference.Shared.csproj" />
        <ProjectReference Include="..\data\AlasdairCooper.Reference.Api.Data.csproj" />
    </ItemGroup>
</Project>