<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Humanizer" />
      <PackageReference Include="WaffleGenerator.Bogus" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\components\AlasdairCooper.Reference.Components.csproj" />
      <ProjectReference Include="..\shared\AlasdairCooper.Reference.Shared.csproj" />
    </ItemGroup>
</Project>
