<Project Sdk="MSTest.Sdk/4.5.1">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\source-generators\AlasdairCooper.Reference.SourceGenerators.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Basic.Reference.Assemblies.Net100" />
      <PackageReference Include="Microsoft.CodeAnalysis.Analyzers">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
      <PackageReference Include="Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing" />
      <PackageReference Include="Microsoft.CodeAnalysis.Testing.Verifiers.MSTest" />
    </ItemGroup>

</Project>
