<Project Sdk="Microsoft.NET.Sdk.Razor">
    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
    <ItemGroup>
      <PackageReference Include="Blazored.LocalStorage" />
      <PackageReference Include="Humanizer.Core" />
      <PackageReference Include="Microsoft.AspNetCore.Components" />
      <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" />
      <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
      <PackageReference Include="Microsoft.JSInterop" />
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\shared\AlasdairCooper.Reference.Shared.csproj" />
    </ItemGroup>
    
    <ItemGroup>
      <Content Update="Inputs\Select.razor.css">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Utilities\Spacer.razor.css">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Accordions\Accordion.razor.css">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Accordions\Accordions.razor.css">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
    </ItemGroup>
</Project>
